language: android
sudo: required
jdk: oraclejdk8

android:
  components:
  - android-28
  - build-tools-28.0.3
  - tools
  - extra
  - extra-google-m2repository
  - extra-android-m2repository

env:
  global:
  # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
- ./gradlew clean assembleDebug assembleRelease testDebug createDebugUnitTestCoverageReport --stacktrace

after_success:
# Codecov.io
- bash <(curl -s https://codecov.io/bash)